const CONNECT = "CONNECT";
const DISCONNECT = "DISCONNECT";
const CHAT = "CHAT";
const YT_PLAY = "YT_PLAY";
const YT_PAUSE = "YT_PAUSE";
const CHANGE_VIDEO = "CHANGE_VIDEO";
const CLIENT_LIST = "CLIENT_LIST";
const VIDEO_ID_HANDSHAKE = "VIDEO_ID_HANDSHAKE";

export {
  CONNECT,
  DISCONNECT,
  CHAT,
  YT_PLAY,
  YT_PAUSE,
  CHANGE_VIDEO,
  CLIENT_LIST,
  VIDEO_ID_HANDSHAKE
};
